### ISSUE TITLE
Override to force yaml creation on midi load even when not properly "BMP" formatted.

### ISSUE THREAD

**Issue by Meowchestra** [MogAmp/MogAmp#14]
Would it be possible to add a checkbox to force a yaml creation on midi load in MogNotable even when tracks are not properly formatted to BMP's instrument names? I sometimes load clean midis from various sources and Notable is not able to load it to  create a yaml configuration unless tracks are named in the ``.mid``. This forces me to manually create a ``.yml`` and write in all the  information, track numbers, and what instrument / octave it's suppose to play at. Alternatively -- forces me to load the midi into an editor such as MidiEditor, name all tracks to "BMP's" format, then import into Notable.

This seems counter-intuitive because you must then know of another application's format when you may only want to use MogMusic tools.

Defaulting all tracks to ``instrument: Piano`` set on ``octave: 3`` just to fill in a blank starting template would help speed up testing new songs in Notable's previewer.

_Issue may be superseded by a built-in file editor with options instead._

**Comment by MoogleTroupe** [comment]
MogLib now creates unknown tracks with instrument type "None" by default.
