### ISSUE TITLE
Digitally sign all executables on compile.

### ISSUE THREAD

**Issue by Meowchestra** [MogAmp/MogAmp#16]
_Suggestion taken from discord._

Digitally sign all executables when distributing? VirusTotal checks on all applications show up as no signature being found.

**MogAmp**
https://www.virustotal.com/gui/file/b66b5c6e825fe50ee4bd32aeafaa2677da4c652900f9dea6064e8010f89b5daf/details
**MogDoot**
https://www.virustotal.com/gui/file/de064ada4b6a7dbbf28fbbb6bc5499d254ee65efe09a891335643fabb5cf2690/details
**MogNotable**
https://www.virustotal.com/gui/file/c8b1f2b718b01e6e999c524a27bbda005afe4fdfcf662c97ea6de4744ee4982a/details
**ChocoSniff**
https://www.virustotal.com/gui/file/e793658bec1061ca5af8473aed3aa1e8fc759dced29a6aa4069327732dbb3901/details

Not sure of the complexity or if it's even an issue, but figured I'd post an issue ticket about it so you can decide.

![link](https://i.imgur.com/pDTen4F.png)
https://github.com/stufus/certerator

**Comment by MoogleTroupe** [comment]
A real code Signing certificate has been purchased and will be used
