### ISSUE TITLE
ChocoSniff creates leftover running executables when you close out of clients.

### ISSUE THREAD

**Issue by Meowchestra** [MogAmp/MogAmp#20]
1) Launch FFXIV client 1.
2) Launch FFXIV client 2.
3) Launch MogAmp
4) Launch MogDoot

Task manager shows 2 running ChocoSniff (32 bit) apps running under MogDoot.

5) Close FFXIV client 2.

A new ChocoSniff app is created (+1) under MogDoot and then 1 is removed.

6) Close FFXIV client 1.

A new ChocoSniff app is created (+1) under MogDoot and then 1 is removed. You now have 2 ChocoSniffs running under Doot with no games opened.

7) Launch FFXIV client 1.

A new ChocoSniff app is created (+1) under MogDoot. You now have 3 ChocoSniffs running under Doot with only 1 game client running.

![link](https://i.imgur.com/eN3BPux.png)

This gets crazier when you have 21 clients and open new / close them at various times when you start Doot with only 8 running initially.

---

Issue discovered from initial report to discord. ChocoSniff blew up when I added a remote connection of someone while having local clients opened and shut down some clients. Only had 8 clients opened total + the 1 remote. Started turning off clients after I connected to them.

![link2](https://i.imgur.com/OOtxhXY.png)

I restarted Doot & Amp and connected to someone. Then after a while got a disconnect but had 4 ChocoSniff running under doot + 4 in background processes when it's just my 1 local client and their remote connection. I ended all the background process ChocoSniffs and a 5th one popped up under Doot. The log in Amp showed disconnect messages multiple times so I wondered if it's creating a new Choco for every time it disconnects.

![link3](https://i.imgur.com/tmfIPck.png)

**Comment by MoogleTroupe** [comment]
packet sniffing system revamp prevents this type of issue going forward
