### ISSUE TITLE
Multiple connected messages on application start with numerous network adapters.

### ISSUE THREAD

**Issue by Meowchestra** [MogAmp/MogAmp#22]
If you have multiple network adapters in use, such as if you use a VPN client, MogAmp/MogDoot outputs connected messages multiple times. I assume this would occur for every adapter active but I only have and can test with 2 (Ethernet + VPN).

![link](https://i.imgur.com/YEcI4W8.png)

Would it be possible to catch this and only output verbose / try connections once? Using the current active network adapter to tunnel / route connections.

_Presumed caused by the multi-adapter fix a couple versions ago._

**Comment by MoogleTroupe** [comment]
connection system is being replaced and this will no longer be an issue
