### ISSUE TITLE
Mousing over a windowed game after clicking play prevents ensemble from being enabled.

### ISSUE THREAD

**Issue by Meowchestra** [MogAmp/MogAmp#25]
If you click ``Play`` to start ensemble but move your mouse over a client that is in windowed mode (party leader local main client or remote clients), ensemble never actually engages and it doesn't play. You have to keep your mouse off the client long enough until ensemble starts / playing begins to prevent issues.

Is there any way to work around this problem?

**Comment by MoogleTroupe** [comment]
not fixable
