### ISSUE TITLE
Exporting mmsong format to yaml or edit mode UI functionality for easier song adjusting.

### ISSUE THREAD

**Issue by Meowchestra** [MogAmp/MogAmp#5]
For song distribution, some people may only upload the ``.mmsong`` file. If you wish to make any tweaks or changes to the song or have long-term future compatibility such as if new better assigned instruments get added or more octaves ever added, you can't edit the file with ease. 

To work around this, _you can_ load the mmsong file with the export to BMP mid checked, then load the BMP mid to generate a yaml. However this seems to cause some loss of information or changes to the song tempo data when it's re-converted to mmsong - it ends up a different size than the original .mmsong file.

Having some type of functionality to edit songs more easily would be nice.

**Comment by MoogleTroupe** [comment]
added to MogLib
