### ISSUE TITLE
libzt being created in two separate directories.

### ISSUE THREAD

**Issue by Meowchestra** [MogAmp/MogAmp#8]
Not sure if intended but noticed that ``libzt.dll`` is being created and used twice in two different directories. 

When you launch MogAmp-RC4, MogLib folder in ``C:\ProgramData\MogLib`` is created with ``libzt.dll`` inside. When you launch MogDoot-RC4, ``libzt.dll`` is generated in the MogMusic folder at ``C:\Users\PC\AppData\Local\MogMusic``. Would it be possible to unify this when all applications are merged together and use the same singular directory / dependency files?

**Comment by MoogleTroupe** [comment]
overhaul of backend library has this resolved now
